version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
  
  redis:
    image: "redis:alpine"